### ISSUE TITLE
ihan oikeita vikoja

### ISSUE THREAD

**Issue by Mapukto** [JiiHu/Tenttiarkisto#35]
- kurssien lisäämiseen ei ole nappia missään.
- kurssia lisättäessä ei voi valita aineta.
- aineiden edit ei toimi.
- jos lisää examin kun ei ole rekisteröitynyt niin tulee error sivu

**Comment by JaniL** [comment]
#36 fiksaa aineiden editin, väärä muuttujanimi koodissa.

**Comment by psaikko** [comment]
https://github.com/JiiHu/Tenttiarkisto/pull/38 lisää napin kurssien lisäämiseen järjestö- ja superkäyttäjille

**Comment by psaikko** [comment]
#39 korjaa exam lisäys errorin
