### ISSUE TITLE
Frontpage remembers previous search

### ISSUE THREAD

**Issue by JaniL** [JiiHu/Tenttiarkisto#42]
If you search for subjects and then go to frontpage, frontpage remembers what you've searched earlier and makes a search based on your previous search.

how to reproduce:
1. open frontpage (as incognito)
2. search for some subject
3. open frontpage again (http://tentit.fi/)
4. magic

**Comment by psaikko** [comment]
Fixed in https://github.com/JiiHu/Tenttiarkisto/commit/38f5947758e3330bf44487bf78a7514150bcecdd
